Djan/trail/post/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='post'

urlpatterns = [
    path('post/', views.post_list , name="list"),
    path('post/<slug:slug>/', views.post_page, name="pages"),
    path("new-post/", views.new_post, name="new_post")
]

Djan/trail/trail/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
import debug_toolbar
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('',views.home),
    path('about/',views.about, name='about'),
    path('blog/', include('post.urls')),
    path('users/', include('users.urls')),

]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Djan/trail/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

Djan/trail/post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)
    banner=models.ImageField(default='fallback.png',blank=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

Djan/trail/users/models.py
from django.db import models

# Create your models here.

Djan/trail/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'slug', 'banner']
        
        

Djan/trail/post/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/post_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'posts': post})
    # return HttpResponse(slug)

@login_required(login_url='/users/login/')
def new_post(request):
    if request.method == 'POST':
        print('POST')
        form=forms.PostForm(request.POST, request.FILES)
        if form.is_valid():
            print('VALID')
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('post:list')
        else:
            return HttpResponse('Invalid form')
    else:
        print('GET')
        form=forms.PostForm()
        return render(request, 'posts/post_new.html',{'form':form})

Djan/trail/trail/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    # return HttpResponse("Hello, world. You're at the polls index.")
    return render(request, 'home.html')

def about(request):
    # return HttpResponse("About")
    return render(request, 'about.html')

Djan/trail/users/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST": 
        form = UserCreationForm(request.POST) 
        print("Hello")
        if form.is_valid(): 
            login(request, form.save())
            return redirect("post:list")
        
        else:
            print("Not valid")
            print(form.errors)
    else:
        form = UserCreationForm()
    return render(request, "register.html", { "form": form })

def login_view(request):
    # return render(request, "login.html")
    if request.method == "POST":
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("post:list")
        else:
            print(form.errors)
    else: 
        form=AuthenticationForm()
    return render(request, "login.html", { "form": form })

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("post:list")

Djan/trail/post/templates/posts/post_list.html
{% extends "layout.html" %}

{% block title %}
    Post List
{% endblock title %}

{% block content %}

    <h1>Post List</h1>

    <div >
 
        {% for post in posts %}
        <article>
            <h2>
                <a href="{% url "post:pages" slug=post.slug %}">
                {{ post.title }}
                </a>
            </h2>
          
            <p style="text-align:left">{{post.date}}</p>
            <p style="text-align:left">{{post.author}}</p>
            <p style="text-align:left">{{ post.content|truncatewords:5 }}</p>
        </article>
        <br>
        {% endfor %}
    </div>
  
{% endblock %}

Djan/trail/post/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
    New Post
{% endblock title %}

{% block content %}
    <h1>New Post</h1>
    <form class="form-with-validation" action="/blog/new-post/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}


    

Djan/trail/post/templates/posts/post_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/index.js' %}" defer></script>
    <title>{{posts.title}}</title>
</head>
<body>
    <h1>{{posts.title}}</h1>
    <p>{{posts.date}}</p>
    <img src="{{posts.banner.url}}" alt="{{posts.title}}" style="max-width: 800px; height: auto; display:block;">
    <p style="text-align:left;">{{posts.content}}</p>
    <br>
    <a href="{% url "post:list" %}">Back to Post List</a>

</body>
</html>

Djan/trail/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block content %}
  <h1>About</h1>
{% endblock %}

Djan/trail/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
  <h1>Hello</h1>
{% endblock %}

Djan/trail/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Django App {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/index.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <ul>
        <a href="/">
          <span role='img' aria-label="Home">🏠</span>
        </a>
        |
        <a href="{% url "about" %}">😀</a>
        |
        <a href="{% url "post:list" %}">📰</a>
        |
       
        {% if user.is_authenticated %}
        <a href="{% url 'post:new_post' %}">
          <span role="img" aria-label="New Post" title="New Post">📝</span>
        </a>
        |
        <form class="logout" action="{% url "users:logout" %}" method="post">
          {% csrf_token %}
          <button class="logout" type="submit" aria-label="logout">
            <span role="img" aria-label="Logout" title="Logout">🚪</span>
          </button>
        </form>
        {% else %}
          <a href="{% url 'users:register' %}">
            <span role="img" aria-label="User Registration" title="User Registration">🚀</span>
          </a>
          |
          <a href="{% url 'users:login' %}">
            <span role="img" aria-label="User Login" title="User Login">🔒</span>
          </a>
        {% endif %}
      </ul>
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

Djan/trail/users/templates/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <section>
        <h1>User Login</h1>
        <form class="form-with-validation" action="/users/login/" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <button class="form-submit">Submit</button>
        </form>
    </section>
  
{% endblock %}

Djan/trail/users/templates/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
  <section>
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
  </section>
{% endblock %}